### ISSUE TITLE
Is Time Range possible?

### ISSUE THREAD

**Issue by sulisu** [aardappel/procrastitracker#108]
Hi,

Is it possible to add a feature to Specify Time Range in addition to Date Range? So users can check what app they have use in the last hour or last 30 minutes.

Now, I make a batch to kill existing procratitracker, then delete all database file, then restart it. I run this batch before every pomodoro work time.

Thanks a lot.

**Comment by aardappel** [comment]
That is not currently in the UI, and would not be easy to add either, because the way PT stores time for a day is with all time for an app accumulated into 1. So if you used App1 for an hr in the morning, then again for another in the afternoon, all it would know is that you used it for 2 hrs that day (and its start time).

We would need to add an option to track non-adjacent time segments first, somehow, which would change the database format (and make the database a lot bigger in many cases).

**Comment by sulisu** [comment]
It seems I have to stick with my workaround.

May I ask other 2 questions based on my workaround:

1) Is it possible to run 2 instances of procrastitracker?

Now the second instance will alert "already running" on startup. Will two running instances of Procrati cause conflict? I have tried to run instances from two copy of program folders, result is the same.

2) If two instances is allowed, and each instance can keep its own database in difference position. Is it possible that one instance runs as usual, keep a long-term record, while the other instance runs with my batch file workaround to provide short-term record?

**Comment by aardappel** [comment]
Yes, they would conflict, they'd try and read and write the same database. Even if you solved that, they'd both try to install the same keyboard/mouse activity hooks in the system, and possibly other things.
