### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by Eliasyoussef47** [aardappel/procrastitracker#61]
The program crashes seemingly randomly. I've noticed it almost every time when I close a game (The Outer Worlds to be exact) and go to check how long I have been playing it that day, But I just had it crash after closing PhpStorm.

How it looks like:
I close a game. I right click ProcrastiTracker's NotifyIcon, the context menu opens but it's unclickable, if I click it crashes and windows asks me if I want to close the program.

**Comment by aardappel** [comment]
Hmm, I've pretty much never had it crash, or receive reports that it does, in its near 10 years of existence.. can you think of anything non-standard that may be running on your computer, especially things that may affect window/ui/input stuff?

I've also used it with hundreds of games, including the Outer Worlds, and never a problem :) Though it doesn't seem to have registered time for Outer Worlds, strangely enough.

**Comment by andre-dana** [comment]
This also happen to me a few times, generally it happens after a idling for a while. It is more towards not responding while showing 'what have you been doing in the last xx minutes' windows. Procrastitracker can be restarted afterwards and only time since idling is missing. I can try to reproduce and record the exact scenario for the crash if @aardappel is interested in it. Not a big issue imo, only slight annoyances. I love procrastitracker! it make me realize how much I actually spend on the net over the week. Btw do you have a donation link?

**Comment by aardappel** [comment]
Yes, and exact repro case would be good, though it is not a given that it happens the same way on each computer.

And thanks! I don't have donation set up for PT specifically. I have a github sponsors account, but don't feel obliged to use it :)

**Comment by aardappel** [comment]
Thanks @andre-dana ;)

**Comment by andre-dana** [comment]
> Thanks @andre-dana ;)

You're welcome! It's not much, but mostly it's to show my appreciation. I can't create an exact repro case, it didn't crash at all in the last few days.

**Comment by Eliasyoussef47** [comment]
I'm sorry for not responding to or updating this issue, I completely forgot about it.

I was able to solve this by searching for everything mentioning the program's name and deleting them.
I then reinstalled the program and it has been working flawlessly since.
