### ISSUE TITLE
There seems to be a bug about recording the away time

### ISSUE THREAD

**Issue by InfinityShu** [aardappel/procrastitracker#84]
![image](https://user-images.githubusercontent.com/31622007/144713928-1403d2cb-637a-48c0-a131-ae4c654f01ec.png)
![image](https://user-images.githubusercontent.com/31622007/144713934-8d11c4b2-41e9-4343-887d-471c3aeb86dd.png)
This was my yesterday's record and I have no idea why I've got a record of 74-hour away time. 
![image](https://user-images.githubusercontent.com/31622007/144713979-a1141deb-2fec-4978-a49f-35df6f583941.png)
Although this makes it hard to check the overall proportion of my laptop usage, it's not a big problem and I'm just curious about why this happened. It did happen one time in the past, with a 46-hour away time record. Is it possible to prevent this from happening?Thank you for taking your time to read my request!

**Comment by aardappel** [comment]
What are the two "away" settings set to in advanced settings?

**Comment by aardappel** [comment]
Ok, just found a potential bug that may have caused this. If waking up from away time was done by multiple mouse button or wheel clicks before the mouse was moved, the time could have been counted multiple times.

Fixed in https://github.com/aardappel/procrastitracker/commit/d49e251484ffdec1b0fe0075feb184ee216783d0

Now the away will only register when the mouse moves, as was the intention before.

**Comment by InfinityShu** [comment]
Thank you! And, is it possible to delete that record?

**Comment by aardappel** [comment]
Look for "keyboard shortcuts" in https://strlen.com/procrastitracker/
